#  File:    Makefile
#  Author:  Jeff Moore
#  Date:    April 5, 2014
#
#  Here's a Makefile


DEBUG	= 	-O2
CC	= 	gcc
INCLUDE	= 	-I/usr/local/include
FLAGS   = 	$(DEBUG)
SOURCE	= 	reader.c
OBJ 	=	$(SOURCE:.c=.o)
SOURCE2 =	gpio.c gpio_pwm.c
OBJ2	=	$(SOURCE2:.c=.o)
LIBS	=	-lpthread

all:		pipeReader

pipeReader:	$(OBJ)
		@echo [Link pipeReader]
		@$(CC) -o $@ $(OBJ) $(LIBS)

.c.o:		
		@echo [Compile] $<
		@$(CC) -c $(FLAGS) $< -o $@

clean:
		@echo "[Clean]"
		@rm -f $(OBJ) pipeReader

install:
		@echo "[Install]"

uninstall:
		@echo "[UnInstall]"
